# Generated by Django 4.1 on 2022-10-07 10:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(default='')),
                ('startDate', models.DateField(verbose_name='Project Start Date')),
                ('expectedDate', models.DateField(verbose_name='Estimated Completion Date')),
                ('completed', models.BooleanField(default=False)),
                ('completionDate', models.DateField(default=datetime.date.today, verbose_name='Completion Date')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_project_set', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('startDate', models.DateField(verbose_name='Task Start Date')),
                ('expectedDate', models.DateField(default=datetime.date.today, verbose_name='Estimated Completion Date')),
                ('weight', models.IntegerField()),
                ('completionDate', models.DateField(default=datetime.date.today, verbose_name='Completion Date')),
                ('completed', models.BooleanField(default=False)),
                ('Type', models.CharField(choices=[('BG', 'BUG'), ('FT', 'FEATURE'), ('RT', 'REFACTOR'), ('MG', 'MIGRATE')], default='FT', max_length=2)),
                ('active', models.BooleanField(default=False)),
                ('Assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.project')),
            ],
        ),
        migrations.CreateModel(
            name='TaskRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.task')),
                ('toUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
